version: '3'

volumes:
  node_modules:

services:
  ldap-auth-proxy:
    image: agate/ldap-auth-proxy
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
      - node_modules:/app/node_modules
    env_file:
      - env
    ports:
      - 3000:3000
